### ISSUE TITLE
Newer pip required on CentOS 7.3?

### ISSUE THREAD

**Issue by verdurin** [gc3-uzh-ch/elasticluster#433]
Now that the `pbr` problems have been fixed, I see this error on a CentOS VM, when launching from a fresh virtualenv:
```
(elasticluster)[centos@adamtest3 src]$ elasticluster
Traceback (most recent call last):
  File "/home/centos/src/venv/elasticluster/bin/elasticluster", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/centos/src/venv/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/home/centos/src/venv/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/home/centos/src/venv/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/centos/src/venv/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/home/centos/src/venv/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/centos/src/venv/elasticluster/lib/python2.7/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'functools32' distribution was not found and is required by jsonschema
```

**Comment by riccardomurri** [comment]
I cannot reproduce this on Ubuntu 16.04 so this time it must be related to `pip` or `setuptools` as provided on CentOS.

Can you please post:

- version of `pip` that you're running?
- version of `setuptools` that's installed in the virtualenv? (`pip freeze | fgrep setuptools`)

**Comment by verdurin** [comment]
Just running:
```
pip install functools32
```
removes the error.

**Comment by riccardomurri** [comment]
Sure :-) the issue is: why is this not detected by `pip` when it installs `jsonschema`?  (It does on my Ubuntu 16.04 laptop)

**Comment by verdurin** [comment]
`pip` inside the virtualenv is `1.4.1`. It's not installed on the VM.

`setuptools` doesn't come up in the `freeze` list. If I run `pip list | grep setuptools` it's:

`35.0.2`

**Comment by riccardomurri** [comment]
`pip==1.4.1` is ancient... Do you get the same error if you run `pip install -U pip` in the virtualenv *before* installing ElastiCluster?

**Comment by verdurin** [comment]
In case it's relevant, I'd had to apply the workaround first:
`pip install six packaging appdirs; pip install --upgrade setuptools`

Will test that now.

**Comment by verdurin** [comment]
Yes, with that upgrade in place, the other dependencies are picked up successfully.

**Comment by riccardomurri** [comment]
It looks like `pip` can correctly upgrade itself... I have pushed a tentative fix on branch "issues/#433" of repo http://github.com/riccardomurri/elasticluster -- can you please test it?

**Comment by verdurin** [comment]
That does work for upgrading `pip`, thanks, though it doesn't solve the `functools32` problem, which *was* solved when I upgraded `pip` manually.

**Comment by verdurin** [comment]
Confirmed with a second run. The `pip` upgrade of itself succeeds, but it doesn't seem to run with the newly-upgraded version, because the `functools32` dependency isn't picked up.

**Comment by riccardomurri** [comment]
Well, then I guess the only solution is to add yet another manual preparation step in the documentation of the install procedure. *sigh*
