### ISSUE TITLE
Deploy shell profile snippets to load Lmod failed

### ISSUE THREAD

**Issue by blue-moon22** [gc3-uzh-ch/elasticluster#578]
Hi there,

**I have installed 1.3.dev5 and I get the following errors:**

TASK [lmod : Deploy shell profile snippets to load Lmod] *************************************************************************************
failed: [frontend001] (item={u'source_cmd': u'.', u'shell': u'sh', u'script': u'profile'}) => {"changed": false, "item": {"script": "profile", "shell": "sh", "source_cmd": "."}, "msg": "Unsupported parameters for (file) module: validate Supported parameters include: _diff_peek, _original_basename, attributes, backup, content, delimiter, directory_mode, follow, force, group, mode, owner, path, recurse, regexp, remote_src, selevel, serole, setype, seuser, src, state, unsafe_writes"}
failed: [frontend001] (item={u'source_cmd': u'source', u'shell': u'csh', u'script': u'cshrc'}) => {"changed": false, "item": {"script": "cshrc", "shell": "csh", "source_cmd": "source"}, "msg": "Unsupported parameters for (file) module: validate Supported parameters include: _diff_peek, _original_basename, attributes, backup, content, delimiter, directory_mode, follow, force, group, mode, owner, path, recurse, regexp, remote_src, selevel, serole, setype, seuser, src, state, unsafe_writes"}

NO MORE HOSTS LEFT ***************************************************************************************************************************

PLAY RECAP ***********************************************************************************************************************************
compute001                 : ok=52   changed=25   unreachable=0    failed=0   
compute002                 : ok=52   changed=25   unreachable=0    failed=0   
compute003                 : ok=52   changed=25   unreachable=0    failed=0   
compute004                 : ok=52   changed=25   unreachable=0    failed=0   
compute005                 : ok=52   changed=25   unreachable=0    failed=0   
frontend001                : ok=86   changed=45   unreachable=0    failed=1   

2018-08-26 23:39:42 vicky-XPS-13-9360 gc3.elasticluster[25752] ERROR Command `ansible-playbook --private-key=/home/vicky/.ssh/google_compute_engine /home/vicky/elasticluster/src/elasticluster/share/playbooks/site.yml --inventory=/home/vicky/.elasticluster/storage/gridengine.inventory --become --become-user=root -v -e @/tmp/extra_vars.yml` failed with exit code 2.
2018-08-26 23:39:42 vicky-XPS-13-9360 gc3.elasticluster[25752] WARNING The cluster has likely *not* been configured correctly. You may need to re-run `elasticluster setup`.
2018-08-26 23:39:42 vicky-XPS-13-9360 gc3.elasticluster[25752] WARNING Cluster `gridengine` not yet configured. Please, re-run `elasticluster setup gridengine` and/or check your configuration

WARNING: YOUR CLUSTER `gridengine` IS NOT READY YET!

Cluster name:     gridengine
Cluster template: gridengine
Default ssh to node: frontend001
- compute nodes: 5
- frontend nodes: 1

To login on the frontend node, run the command:

    elasticluster ssh gridengine

To upload or download files to the cluster, use the command:

    elasticluster sftp gridengine

**My config file is this:**

# Gridengine software to be configured by Ansible
[setup/ansible-gridengine]
provider=ansible
frontend_groups=gridengine_master
compute_groups=gridengine_worker
global_var_insecure_https_downloads=yes

# Create a cloud provider (call it "google-cloud")
[cloud/google-cloud]
provider=google
gce_project_id=aaa              
gce_client_id=bbb
gce_client_secret=ccc       
noauth_local_webserver=True
zone=europe-west2-c

# Create a login (call it "google-login")
[login/google-login]
image_user=ddd                                           
image_user_sudo=root
image_sudo=True
user_key_name=elasticluster
user_key_private=~/.ssh/google_compute_engine
user_key_public=~/.ssh/google_compute_engine.pub

# Bring all of the elements together to define a cluster called "gridengine"
[cluster/gridengine]
cloud=google-cloud
login=google-login
setup=ansible-gridengine
security_group=default
image_id=debian-9-stretch-v20180820
flavor=n1-highmem-4
frontend_nodes=1
compute_nodes=5
ssh_to=frontend
boot_disk_size=100

[cluster/gridengine/frontend]
boot_disk_type=pd-ssd
boot_disk_size=500

Thanks!

**Comment by riccardomurri** [comment]
Can you please upgrade to latest "master" and try again?  It should be fixed now.

**Comment by loveshack** [comment]
This still fails with the current master (with CentOS 7):
```
  TASK [lmod : Deploy shell profile snippets to load Lmod] ***********************                                                                             
  task path: /home/mdehsdl3/elasticluster/elasticluster/share/playbooks/roles/lmod/tasks/post-install.yml:28                                                   
  failed: [frontend001] (item={u'shell': u'sh', u'script': u'profile'}) => {"changed": false, "gid": 0, "group": "root", "item": {"script": "profile", "shell": "sh"}, "mode": "0644", "msg": "refusing to convert from file to symlink for /etc/profile.d/modules.sh", "owner": "root", "path": "/etc/profile.d/modules.sh", "size": 168, "state": "file", "uid": 0}                                       
  changed: [frontend001] => (item={u'shell': u'csh', u'script': u'cshrc'}) => {"changed": true, "dest": "/etc/profile.d/modules.csh", "gid": 0, "group": "root", "item": {"script": "cshrc", "shell": "csh"}, "mode": "0777", "owner": "root", "size": 24, "src": "/opt/lmod/7.0/init/cshrc", "state": "link", "uid": 0}
```

I don't see why it's necessary as the Lmod packages in EPEL and Debian stable are recent enough, according to the easybuild doc.  Also, it probably should only be done as a dependency of easybuild, not unconditionally; there have been problems with interaction between environment-modules and lmod.

**Comment by riccardomurri** [comment]
> I don't see why it's necessary as the Lmod packages in EPEL and Debian stable are recent enough, according to the easybuild doc.

Does CentOS 6 also have recent Lmod packages?  But I get your point, I'll see whether I can install from repos and fall-back to source installs on CentOS 6.

> it probably should only be done as a dependency of easybuild, not unconditionally; there have been problems with interaction between environment-modules and lmod.

My intention was to replace `environment-modules` altogether and always have Lmod.  If people want the choice, then EB runs fine with the TCL-based environment modules too.

Thoughts?

**Comment by riccardomurri** [comment]
(Anyway, @loveshack your error seems to be different from the one originally reported -- in https://github.com/gc3-uzh-ch/elasticluster/issues/578#issuecomment-458091667 Ansible complains that `/etc/profile.d/modules.sh` already exists as a symlink; the initial report was about using the wrong action module.)

**Comment by loveshack** [comment]
> Does CentOS 6 also have recent Lmod packages?  But I get your point,
> I'll see whether I can install from repos and fall-back to source
> installs on CentOS 6.

I thought it was the same as epel7, but it's actually behind.  I can
probably get it updated with a good reason.

>> it probably should only be done as a dependency of easybuild, not
>> unconditionally; there have been problems with interaction between
>> environment-modules and lmod.
>
> My intention was to replace `environment-modules` altogether and
> always have Lmod.

That's probably not unreasonable, but EL7 openmpi and mpich (at least)
depend explicitly on environment-modules, so you have them anyhow.  It's
different in Fedora, and possibly EL8, which I'd have to fire up to
check.

> If people want the choice, then EB runs fine with
> the TCL-based environment modules too.
>
> Thoughts?

I guess at least in EL7 there's no problem, then, as it will work with
what's installed anyhow, and people can choose to install Lmod too if
that's not a problem; it may be that the problem I found was just with
the version from epel6.  (For those of us who still need to figure out
ansible, it might be useful to have an example of using the private
roles to install other packages without hacking hpc-common.)  I can't
immediately check the version of environment-modules in el6 either.

From a quick check on Debian stable, it looks as if you can just use
lmod, which conflicts with environment modules.

I just removed the Lmod build from the configuration, of course, once I
found it.  [I don't know easybuild, as it's not a package system.]

**Comment by loveshack** [comment]
> (Anyway, @loveshack your error seems to be different from the one
> originally reported -- in
> https://github.com/gc3-uzh-ch/elasticluster/issues/578#issuecomment-458091667
> Ansible complains that `/etc/profile.d/modules.sh` already exists as a
> symlink; the initial report was about using the wrong action module.)

Yes, which is why I included it.  The Lmod installation still/currently
breaks the cluster startup, and it seemed appropriate to add to the open
issue.  Perhaps I should have opened a new one.

**Comment by riccardomurri** [comment]
@loveshack I cannot reproduce your issue with Lmod on CentOS7; everything runs to successful completion here.  I'm using a "CentOS 7.6.1810" image, downloaded on Jan 24, 2019 from http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2

**Comment by loveshack** [comment]
I couldn't check this earlierfor local reasons.  It's reproducible for
me with a current pull of elasticluster, using AWS with:

  ec2_region=eu-west-1

  image_id=ami-0879d97613ba8075a

This is an EL7 image with various things pre-installed, including
environment-modules (via openmpi, at least), but I don't know why the
installed packages would make a difference.

I think Lmod should only be a dependency of easybuild, but the current
setup just looks wrong.  Lmod is a high enough version for easybuild in
EPEL and Debian 9 (current stable), so there's no reason to try to build
it (and install lua bits explicitly) except on Debian oldstable.  The
profile snippets are clearly wrong for the packaged version.  I haven't
tried to analyze and fix this, particularly as I don't know ansible.  I
just commented out the dependency from hpc-common to get it working at
all.

**Comment by verdurin** [comment]
Maybe worth pointing out that it's only very recently that the EPEL build of `Lmod` has caught up. For a very long time it was very old. 
I also found I needed to comment out the `Lmod` shell snippet code because in large part it clashed with the package contents.

**Comment by verdurin** [comment]
I suppose my point was that lots of people didn't bother with the EPEL `Lmod`, even though it was new enough for `easybuild`, because it was so old.

**Comment by loveshack** [comment]
OK, but there's always the option of pestering for package updates, but it's pretty recent in EPEL7.  (The increasing pain of Fedora maintenance puts me off offering to do updates on anything else, but I have copr rebuilds of a few things.)

**Comment by riccardomurri** [comment]
It is incorrect to say that Lmod is only used for EasyBuild in ElastiCluster; a `module` command is also used/needed when installing Rmpi and for Anaconda 2/3.  Quite frankly, I find it very convenient to use and would like to introduce it whenever different versions of the same software may co-exist and be end-user selectable; think of Spark as an example.  So, actually, it is more likely that Lmod becomes a dependency of role `common` than of role `easybuild`.

That said, at the moment the dependency (for both Rmpi and EasyBuild) is that a `module` command exists and is working, so in principle I can change the code to just test for `module` and only deploy Lmod if it's missing.  However, the original environment-modules command uses TCL scripts to define modules whereas Lmod uses Lua ones and I would prefer not maintain 2 versions of the same thing.  It's quite likely that I can just use TCL for both, but I need to check -- otherwise I need to have a way to determine which of the two versions is in use.

**Comment by riccardomurri** [comment]
(FWIW, Lmod is installed from source at version 7.0 because that is the first version available on GitHub. Earlier releases are hosted on SourceForge, which does not provide predictable download URLs)

**Comment by loveshack** [comment]
The implication in the code was that Lmod was required for easybuild,
but I don't know where I saw that.

Yes, Fedora-style (but not Debian) MPI packages require a modules
package.  I think that can be satisfied by Lmod in Fedora, but in EL7
it's specifically environment-modules, but Lmod is supposed to work with
Tcl files, and does for openmpi, at least.  There used to be a conflict
in EPEL6, but it's fixed.

[pbdR seems a better option than Rmpi, but it's not in Debian or Fedora;
I should probably have submitted the Fedora packaging.  However,
environment modules for Rmpi in Fedora would have the same issue as pdbR
of missing policy for R MPI packaging.  You probably didn't want to know
that.]

**Comment by loveshack** [comment]
For what it's worth, I don't understand about Lmod downloads, given the
history of the Fedora spec; that has earlier ones from
http://downloads.sourceforge.net/lmod/%{name}-%{version}.tar.bz2 or
https://github.com/TACC/Lmod/archive/%{version}/%{name}-%{version}.tar.gz

**Comment by riccardomurri** [comment]
>  I don't understand about Lmod downloads, given the history of the Fedora spec; that has earlier ones from http://downloads.sourceforge.net/lmod/%{name}-%{version}.tar.bz2 or https://github.com/TACC/Lmod/archive/%{version}/%{name}-%{version}.tar.gz

Well, my bad then -- I must've missed the download pattern on SF.net ...

**Comment by riccardomurri** [comment]
I spent some time checking the OS packages for Lmod and environment-modules; here's a few notes, mainly for reference when implementing a "module" role:

## CentOS 7

Lmod:
- default module directory (used by other OS packages) is `/etc/modulefiles`
- module search path must be customized using shell profile script
- SH-like shells load `/etc/profile.d/z00_lmod.sh`
- CSH-like shells load `/etc/profile.d/z00_lmod.csh`
- EPEL needed

environment-modules:
- default module directory (used by other OS packages) is `/etc/modulefiles`
- module search path must be customized using shell profile script
- SH-like shells load `/etc/profile.d/modules.sh`
- CSH-like shells load `/etc/profile.d/modules.csh`
- in main OS repositories (i.e., no EPEL needed)

The two packages *do not conflict*, so both can be installed at the same time.


## Ubuntu 18.04 ("bionic"), Debian 9 ("stretch")

Lmod:
- default module search path defined by adding lines to `/etc/lmod/modulespath`
- SH-like shells load `/etc/profile.d/lmod.sh`

environment-modules:
- default module search path defined by adding lines to `/etc/environment-modules/modulespath`
- SH-like shells load `/etc/profile.d/modules.sh`
- CSH-like shells load `/etc/csh/login.d/modules`
- version is 4.1.1 on Ubuntu 18.04 and 3.2.10 on Debian 9
- on Debian 9, installing the package brings in a world of dependencies (including GCC, bzip2 and a bunch of libraries...)

The two packages conflict, so installing `lmod` will wipe out `environment-modules` (save for the config files in `/etc`)


## Ubuntu 16.04 ("xenial")

Lmod:
- no shell snippet to load it by default in login shells
- no default system-wide module files directory

environment-modules:
- default module search path defined by adding lines to `/etc/environment-modules/modulespath`
- SH-like shells load `/etc/profile.d/lmod.sh`
- CSH-like shells load `/etc/csh/login.d/modules`
- installing the package brings in a world of dependencies (including GCC, bzip2 and a bunch of libraries...)

The two packages *do not conflict*, so both can be installed at the same time.


## Debian 8 ("jessie")

Lmod:
- **version 5.6.2 is not enough for EasyBuild!**
- no shell snippet to load it by default in login shells
- no default system-wide module files directory

environment-modules:
- default module search path defined by adding lines to `/etc/environment-modules/modulespath`
- SH-like shells load `/etc/profile.d/lmod.sh`
- CSH-like shells load `/etc/csh/login.d/modules`
- installing the package brings in a world of dependencies (including GCC, bzip2 and a bunch of libraries...)

The two packages *do not conflict*, so both can be installed at the same time.


## CentOS 6

Lmod:
- default module directory (used by other OS packages) is `/etc/modulefiles`
- module search path must be customized using shell profile script
- SH-like shells load `/etc/profile.d/z00_lmod.sh`
- CSH-like shells load `/etc/profile.d/z00_lmod.csh`
- EPEL needed

environment-modules:
- default module directory (used by other OS packages) is `/etc/modulefiles`
- module search path must be customized using shell profile script
- SH-like shells load `/etc/profile.d/modules.sh`
- CSH-like shells load `/etc/profile.d/modules.csh`
- in main OS repositories (i.e., no EPEL needed)

The two packages *do not conflict*, so both can be installed at the same time.

**Comment by riccardomurri** [comment]
I think this has now been fixed since commit 3f2c8526: the TCL-based "modules" command is now default, and Lmod is only installed upon request.
